import { Html, Head, Main, NextScript } from "next/document";
import { useTranslation } from "react-i18next";

export default function Document() {
  const { t } = useTranslation();
  return (
    <Html lang="en">
      <Head>
        <title>{t("appTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="%PUBLIC_URL%/fonts/Lato/Lato-Regular.ttf"
          as="font"
          crossOrigin="anonymous"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
