import Head from "next/head";
import { useTranslation } from "react-i18next";
import "@src/localizations";

export default function Home() {
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>{t("appTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Get started by editing</p>
      </main>
    </>
  );
}
